server.address=127.0.0.1
server.port=8080
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.read.strict-duplicate-detection=true
server.error.include-message=never
server.error.include-stacktrace=never
spring.lifecycle.timeout-per-shutdown-phase=10s
